server:
  port: 8080
spring:
  datasource:
    sql-script-encoding: UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.8.100:3306/hy-ss_dev?useUnicode=TRUE&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 6012328
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      initialization-fail-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 2
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    view:
      prefix: /templates
      suffix: .html